language: python

install:
  - pip install -q tox coverage coveralls

script:
  - coverage erase
  - tox

after_success:
  - coverage combine
  - coveralls

notifications:
  email:
    - boerni@gmail.com